Assignment9/Controllers/CoachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assignment9.Controllers
{
    public class CoachController : Controller
    {
        private Manager man = new Manager();
        // GET: Coach
        public ActionResult Index()
        {
            return View(man.CoachesGetAll());
        }

        // GET: Coach/Details/5
        public ActionResult Details(int id)
        {
            return View(man.CoachesGetById(id));
        }

        public ActionResult SearchCoach()
        {
            return View(new CoachSearchForm());
        }

        [Route("Coach/Coaches/{searchText}")]
        public ActionResult Coaches(string searchText = "")
        {
            // Fetch matching tracks
            var c = man.CoachGetByName(searchText);

            if (c == null)
            {
                // Empty list
                return PartialView("_CoachList", new List<CoachBase>());
            }
            else
            {
                return PartialView("_CoachList", c);
            }
        }
    }
}

Assignment9/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assignment9.Controllers
{
    public class PlayerController : Controller
    {
        private Manager man = new Manager(); 
        // GET: Player
        public ActionResult Index()
        {
            return View(man.PlayersGetAll());
        }

        // GET: Player/Details/5
        public ActionResult Details(int id)
        {
            return View(man.PlayerGetById(id));
        }

        public ActionResult Search()
        {
            return View(new PlayerSearchForm());
        }

        [Route("Player/Players/{searchText}")]
        public ActionResult Players(string searchText = "")
        {
            // Fetch matching tracks
            var c = man.PlayerGetByName(searchText);

            if (c == null)
            {
                // Empty list
                return PartialView("_PlayerList", new List<PlayerBase>());
            }
            else
            {
                return PartialView("_PlayerList", c);
            }
        }
    }
}

Assignment9/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MLB Manager - Jordan Hook</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @{
        var userAccount = new Assignment9.Controllers.UserAccount(User as System.Security.Claims.ClaimsPrincipal);
    }
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Assignment 9", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Teams", "Index", "Team")</li>
                    <li>@Html.ActionLink("Players", "Index", "Player")</li>
                    <li>@Html.ActionLink("Coaches", "Index", "Coach")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Jordan Hook</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>